### ISSUE TITLE
Custom settings on per-project basis

### ISSUE THREAD

**Issue by alexdrupal** [amiorin/vim-project#16]
Hello

Nice plugin, by the way. I have a couple of questions:

1) generate/regenerate tags file for project tree (with recursion). Possible?
2) I want to be able to setup some options on project, like in project1 I have 2 spaces indent and on project 2 I have 4 spaces
3) I want to be able to setup different options for plugins. Example:

> let g:snipMate.scope_aliases = {}
> let g:snipMate.scope_aliases['ruby'] = 'ruby,rails'

**Comment by phux** [comment]
For 1:
Check https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html in combination with something like 
`    au BufWritePost *.rb silent! !eval '[ -f ".git/hooks/ctags" ] && .git/hooks/ctags' &
`
Regarding 2 & 3: that's what the callbacks are for, check the sample .vimrc in the README

**Comment by alexdrupal** [comment]
thanks
